terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket         = "infraflow-terraform-state-897722687806"
    key            = "deployments/6a6b8d7afa1bc3f8a37747d6/terraform.tfstate"
    region         = "ap-south-1"
    dynamodb_table = "infraflow-terraform-locks"
    encrypt        = true
  }
}

variable "lambda_source_code_hashes" {
  type    = map(string)
  default = {}
}

provider "aws" {
  region = "ap-south-1"
  default_tags {
    tags = {
      ManagedBy = "infraflow"
    }
  }
}

provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
  default_tags {
    tags = {
      ManagedBy = "infraflow"
    }
  }
}

resource "aws_cloudfront_distribution" "global_cdn" {
  enabled             = true
  comment             = "Static frontend CDN"
  default_root_object = "index.html"
  price_class         = "PriceClass_100"
  web_acl_id          = aws_wafv2_web_acl.edge_waf.arn

  origin {
    domain_name = aws_s3_bucket.frontend_build_bucket.bucket_regional_domain_name
    origin_id   = "s3-frontend_build_bucket"
  }

  default_cache_behavior {
    target_origin_id       = "s3-frontend_build_bucket"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true

    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }
  }

  custom_error_response {
    error_code         = 403
    response_code      = 200
    response_page_path = "/index.html"
  }

  custom_error_response {
    error_code         = 404
    response_code      = 200
    response_page_path = "/index.html"
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}

resource "aws_s3_bucket" "frontend_build_bucket" {
  bucket_prefix = "infraflow-static-"
  force_destroy = true
}

resource "aws_s3_bucket_website_configuration" "frontend_build_bucket_website" {
  bucket = aws_s3_bucket.frontend_build_bucket.id

  index_document {
    suffix = "index.html"
  }

  error_document {
    key = "index.html"
  }
}

resource "aws_s3_bucket_public_access_block" "frontend_build_bucket_public_access" {
  bucket = aws_s3_bucket.frontend_build_bucket.id

  block_public_acls       = false
  block_public_policy     = false
  ignore_public_acls      = false
  restrict_public_buckets = false
}

resource "aws_s3_bucket_policy" "frontend_build_bucket_public_read" {
  bucket = aws_s3_bucket.frontend_build_bucket.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "PublicReadGetObject"
        Effect    = "Allow"
        Principal = "*"
        Action    = "s3:GetObject"
        Resource  = "${aws_s3_bucket.frontend_build_bucket.arn}/*"
      }
    ]
  })

  depends_on = [aws_s3_bucket_public_access_block.frontend_build_bucket_public_access]
}

resource "aws_wafv2_web_acl" "edge_waf" {
  provider = aws.us_east_1
  name  = "infraflow-edge-waf-6a6b8d7afa1bc3f8"
  scope = "CLOUDFRONT"

  default_action {
    allow {}
  }

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "StaticFrontendWebAcl"
    sampled_requests_enabled   = true
  }
}

resource "aws_cloudwatch_metric_alarm" "cdn_5xx_alarm" {
  provider            = aws.us_east_1
  alarm_name          = "infraflow-cdn-5xx-alarm-6a6b8d7afa1bc3f8"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "5xxErrorRate"
  namespace           = "AWS/CloudFront"
  period              = 300
  statistic           = "Average"
  threshold           = 1
}

output "infraflow_resource_outputs" {
  description = "Resource identifiers, ARNs, endpoints, and connectivity values generated by infraflow."
  value = {
    global_cdn = {
      label = "Global CDN"
      service = "CloudFront"
      terraform_address = "aws_cloudfront_distribution.global_cdn"
      id = try(aws_cloudfront_distribution.global_cdn.id, null)
      arn = try(aws_cloudfront_distribution.global_cdn.arn, null)
      domain_name = try(aws_cloudfront_distribution.global_cdn.domain_name, null)
      hosted_zone_id = try(aws_cloudfront_distribution.global_cdn.hosted_zone_id, null)
    }
    frontend_build_bucket = {
      label = "Frontend build bucket"
      service = "S3"
      terraform_address = "aws_s3_bucket.frontend_build_bucket"
      id = try(aws_s3_bucket.frontend_build_bucket.id, null)
      arn = try(aws_s3_bucket.frontend_build_bucket.arn, null)
      bucket_domain_name = try(aws_s3_bucket.frontend_build_bucket.bucket_domain_name, null)
      bucket_regional_domain_name = try(aws_s3_bucket.frontend_build_bucket.bucket_regional_domain_name, null)
      website_endpoint = try(aws_s3_bucket_website_configuration.frontend_build_bucket_website.website_endpoint, null)
      website_domain = try(aws_s3_bucket_website_configuration.frontend_build_bucket_website.website_domain, null)
    }
    edge_waf = {
      label = "Edge WAF"
      service = "WAF"
      terraform_address = "aws_wafv2_web_acl.edge_waf"
      arn = try(aws_wafv2_web_acl.edge_waf.arn, null)
      id = try(aws_wafv2_web_acl.edge_waf.id, null)
      capacity = try(aws_wafv2_web_acl.edge_waf.capacity, null)
    }
    cdn_5xx_alarm = {
      label = "CDN 5xx alarm"
      service = "CloudWatch"
      terraform_address = "aws_cloudwatch_metric_alarm.cdn_5xx_alarm"
      arn = try(aws_cloudwatch_metric_alarm.cdn_5xx_alarm.arn, null)
      id = try(aws_cloudwatch_metric_alarm.cdn_5xx_alarm.id, null)
    }
  }
}