import { z } from 'zod';
import { env } from '../config/env.js';
import { Deployment } from '../models/Deployment.js';
import { ApiError } from '../utils/ApiError.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { terraformValidateDiagnosticsToIssues } from '../services/terraformCliValidator.js';
import { runTerraformDeployment } from '../services/deploymentExecutorDispatch.js';

// Called by terraform-validate.yml's own final step, not a logged-in user — same shared-secret auth
// as terraformDeployCallbackController.js, and registered before requireAuth for the same reason (see
// deploymentRoutes.js). This is what actually moves a deployment out of 'validating': the request that
// dispatched the workflow (githubTerraformValidator.js) only confirms the run started and returns —
// see its own comment for why waiting any longer than that isn't safe inside a Lambda-hosted request.
export const terraformValidateCallbackSchema = z.object({
  body: z.object({
    runId: z.union([z.string(), z.number()]),
    valid: z.boolean(),
    diagnostics: z.array(z.record(z.any())).optional().default([]),
  }),
});

export const receiveTerraformValidateCallback = asyncHandler(async (req, res) => {
  const provided = bearerToken(req);
  if (!env.DEPLOYMENT_CALLBACK_SECRET || provided !== env.DEPLOYMENT_CALLBACK_SECRET) {
    throw new ApiError(401, 'Invalid callback credentials.');
  }

  const { runId, valid, diagnostics } = req.validated.body;
  const deployment = await Deployment.findById(req.params.id);
  if (!deployment) return res.json({ success: true });

  // A stale callback from an earlier, superseded validation run on this same deployment (e.g. the
  // diagram was edited and re-validated before the first run finished) — ignore it rather than let it
  // clobber a newer result.
  if (String(deployment.pendingValidation?.runId ?? '') !== String(runId)) {
    return res.json({ success: true });
  }

  const cliIssues = valid ? [] : terraformValidateDiagnosticsToIssues(diagnostics);
  const structuralIssues = (deployment.validationIssues ?? []).filter((issue) => !isCliIssue(issue));
  const issues = [...structuralIssues, ...cliIssues];
  const blockers = issues.filter((issue) => issue.severity === 'error').length;
  const warnings = issues.filter((issue) => issue.severity === 'warning').length;

  deployment.validationIssues = issues;
  if (deployment.plan) {
    deployment.plan.blockers = blockers;
    deployment.plan.warnings = warnings;
    for (const step of deployment.plan.steps ?? []) {
      if (step.label === 'Run terraform validate') step.status = cliIssues.length ? 'blocked' : 'ready';
      if (step.label === 'Wait for approval' || step.label === 'Deploy to AWS') step.status = blockers ? 'blocked' : 'ready';
    }
  }

  const autoApply = Boolean(deployment.pendingValidation?.autoApply);
  deployment.pendingValidation = undefined;
  deployment.logs.push({
    message: blockers
      ? `GitHub Actions terraform validate run #${runId} found blocking issues.`
      : `GitHub Actions terraform validate run #${runId} passed.`,
    level: blockers ? 'warning' : 'info',
  });

  deployment.status = blockers ? 'draft' : autoApply ? 'queued' : 'draft';
  await deployment.save();

  if (!blockers && autoApply) {
    void runTerraformDeployment(deployment._id);
  }

  res.json({ success: true });
});

// validationIssues mixes structural issues (present from creation) with CLI issues (added here) with
// no discriminator field on the stored objects — every CLI issue's message is generated by
// terraformValidateDiagnosticsToIssues and always starts with this exact prefix, so re-running
// validation can cleanly drop only the previous CLI batch without touching structural issues.
function isCliIssue(issue) {
  return typeof issue?.message === 'string' && issue.message.startsWith('terraform validate');
}

function bearerToken(req) {
  const header = req.headers.authorization ?? '';
  return header.startsWith('Bearer ') ? header.slice('Bearer '.length).trim() : '';
}
